---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: uptime-kuma
  namespace: flux-system
spec:
  chart:
    spec:
      chart: uptime-kuma
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: uptime-kuma
        namespace: flux-system
      version: 2.22.0
  interval: 1m0s
  releaseName: uptime-kuma
  targetNamespace: monitoring
  values:
    ingress:
      enabled: true
      className: "traefik"
      hosts:
        - host: uptime-kuma.ytaya.site
          paths:
            - path: /
              pathType: ImplementationSpecific

