# https://taskfile.dev

version: '3'

includes:
  talos:
    taskfile: .taskfiles/talos.yaml

  ansible: .taskfiles/ansible.yaml
  terraform: .taskfiles/terraform.yaml
  flux: .taskfiles/flux.yaml


tasks:
  default:
    cmds:
      - task --list-all
    silent: true
