
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: homelab
  namespace: argocd
spec:
  sourceRepos:
    - https://github.com/0xTheFr34k/Homelab.git
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wireguard
  namespace: argocd
spec:
  project: homelab
  source:
    repoURL: https://github.com/0xTheFr34k/Homelab.git
    targetRevision: master
    path: argocd_apps/WireGuard
  destination:
    server: https://kubernetes.default.svc
    namespace: wireguard
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
