---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: istiod
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://istio-release.storage.googleapis.com/charts


