apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: metallb
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
      version: "*"
  install:
    createNamespace: true
  targetNamespace: metallb-system
  values:
    config:
      addressPools:
        - name: default
          protocol: layer2
          addresses:
            - 192.168.1.240-192.168.1.250
