---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
  namespace: flux-system
spec:
  chart:
    spec:
      chart: harbor
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: flux-system
      # repo: https://helm.goharbor.io
      version: 1.18.0
  interval: 1m0s
  releaseName: harbor
  targetNamespace: harbor
  upgrade:
    crds: CreateReplace
    disableWait: true
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    expose:
      type: ingress
      tls:
        enabled: true
      ingress:
        hosts:
          core: harbor.ytaya.site
        className: "traefik"

    externalURL: https://harbor.ytaya.site

    registry:
      relativeurls: true

