apiVersion: apps/v1
kind: Deployment
metadata:
  name: wireguard
  namespace: wireguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wireguard
  template:
    metadata:
      labels:
        app: wireguard
    spec:
      containers:
      - name: wireguard
        image: linuxserver/wireguard
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
              - SYS_MODULE
        env:
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          - name: TZ
            value: "Europe/Paris"
          - name: SERVERURL
            value: "192.168.1.101" # use MetalLB IP or WAN IP
          - name: SERVERPORT
            value: "51820"
          - name: PEERS
            value: "1"
          - name: PEERDNS
            value: "auto"
        ports:
        - containerPort: 51820
          protocol: UDP
        volumeMounts:
          - mountPath: /config
            name: wireguard-config
      restartPolicy: Always
      volumes:
        - name: wireguard-config
          persistentVolumeClaim:
            claimName: wireguard-pvc
