---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app portainer
  namespace: flux-system
spec:
  targetNamespace: portainer
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: traefik
    - name: longhorn
  path: ./kubernetes/apps/portainer/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 1m
  timeout: 20m

