
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app pihole
  namespace: flux-system
spec:
  targetNamespace: pihole
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/networking/pi-hole/app
  dependsOn:
  - name: longhorn
  - name: metallb
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 1m
  retryInterval: 1m
  timeout: 5m
