---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: pihole
spec:
  interval: 5m
  chart:
    spec:
      chart: external-dns
      version: 9.0.3
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
      interval: 5m
  values:
    provider: pihole
    registry: noop
    policy: sync
    regexDomainFilter: .*\.ytaya\.site
    regexDomainExclusion: .*\.ytaya\.site
    pihole:
      server: http://192.168.1.101
      secretName: pihole-password-dns
