
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  chart:
    spec:
      chart: traefik
      version: 3.5.0
      sourceRef:
        kind: HelmRepository
        name: traefik
      interval: 1h
  interval: 1h
  releaseName: traefik
