apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cnpg
  namespace: flux-system
spec:
  interval: 5m
  path: ./kubernetes/apps/cnpg/app
  dependsOn:
    - name: longhorn
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: cnpg-system
  wait: true

