apply-config:
  talosctl apply-config -n 192.168.1.40  --file clusterconfig/talos-proxmox-cluster-master-0.yaml --insecure
  talosctl apply-config -n 192.168.1.41  --file clusterconfig/talos-proxmox-cluster-worker-0.yaml --insecure
  talosctl apply-config -n 192.168.1.42  --file clusterconfig/talos-proxmox-cluster-worker-1.yaml --insecure

bootstrap:
  talosctl bootstrap --nodes 192.168.1.40  --endpoints 192.168.1.40  --talosconfig clusterconfig/talosconfig

kubeconfig:
  talosctl kubeconfig  . --nodes 192.168.1.40 --talosconfig clusterconfig/talosconfig


