clusterName: talos-proxmox-cluster
endpoint: https://192.168.1.40:6443
nodes:
  - hostname: master-0
    ipAddress: 192.168.1.40
    installDisk: /dev/vda
    controlPlane: true
  - hostname: worker-0
    ipAddress: 192.168.1.41
    installDisk: /dev/vda
    controlPlane: false
  # - hostname: worker-1
  #   ipAddress: 192.168.1.42
  #   installDisk: /dev/vda
  #   controlPlane: false
controlPlane:
  patches:
  - |-
    - op: add
      path: /machine/kubelet/extraMounts
      value:
        - destination: /var/lib/longhorn
          type: bind
          source: /var/lib/longhorn
          options:
            - bind
            - rshared
            - rw
  schematic:
    customization:
      systemExtensions:
        officialExtensions:
          - siderolabs/iscsi-tools
          - siderolabs/util-linux-tools
worker:
  patches:
  - |-
    - op: add
      path: /machine/kubelet/extraMounts
      value:
        - destination: /var/lib/longhorn
          type: bind
          source: /var/lib/longhorn
          options:
            - bind
            - rshared
            - rw
  schematic:
    customization:
      systemExtensions:
        officialExtensions:
          - siderolabs/iscsi-tools
          - siderolabs/util-linux-tools
