resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  
  # Post Flux-Kustomizations
  - ./metallb/ks.yaml
  - ./traefik/ks.yaml
  - ./pi-hole/ks.yaml
  - ./external-dns/ks.yaml
  - ./cloudflared/ks.yaml
