apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-app
  namespace: flux-system
spec:
  interval: 10m
  path: ./apps/networking/metallb    # adjust to your repo path
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn: []  # nothing before this
  # only include Helm + namespace
  resources:
    - namespace.yaml
    - HelmRepository.yaml
    - HelmRelease.yaml

