apiVersion: v1
kind: Namespace
metadata:
  name: networking
  labels:
    needs-vault: 'true'
    pod-security.kubernetes.io/enforce: 'privileged'
---
apiVersion: v1
kind: Namespace
metadata:
  name: pihole
---
apiVersion: v1
kind: Namespace
metadata:
  name: cloudflared

