---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: flux-system
spec:
  chart:
    spec:
      chart: nextcloud
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: flux-system
      version: 8.3.0
  interval: 1m0s
  releaseName: nextcloud
  targetNamespace: nextcloud
  upgrade:
    crds: CreateReplace
    disableWait: true
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    ingress:
      enabled: true
      labels: {}
      path: /
      pathType: Prefix

    nextcloud:
      host: nextcloud.ytaya.site
      username: admin
      password: changeme
      existingSecret:
        enabled: true
        secretName: nextcloud-secret

    persistence:
      enabled: true
      storageClass: "longhorn"
      accessMode: ReadWriteOnce
      size: 8Gi

      nextcloudData:
        enabled: true
        storageClass: "longhorn"
        accessMode: ReadWriteOnce
        size: 100Gi

