apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      version: "*"
  install:
    createNamespace: true   # ← this line tells Flux to create the target namespace
  targetNamespace: traefik  # ← the namespace where Traefik will be installed
  values:
    dashboard:
      enabled: true
    service:
      type: LoadBalancer

