apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metal-pool
  namespace: networking
spec:
  addresses:
  - 192.168.1.100-192.168.1.120
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: cloud-advertisement
  namespace: networking
spec:
  ipAddressPools:
  - metal-pool
