apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-config
    namespace: cloudflared
stringData:
    config.yaml: ENC[AES256_GCM,data:6OhqOag6SgMrpbxQzyAnlkPjD78VBy4bv53PD9Zgsfn5GGTB8Ci8Hkx8lH4IuR6LdCa7KwG7DJkuzyEcCbSS6wiDVRvcKlNRUnXa64k3V8v+7l580/J9rynmR5qDEL676YSnNZc1miJyaMhKTuPVgatx7JiS6Dyg6SqfQ5FoRVMHajLKbupRfK8nzzaFLvmxkrb3tXnpba0Yk5NBFGkSN94SglQmPbPOmjTCRoA1tfXyHu2figYaTozFuyFmSUtXPA+7lA9VYD6wu6/VLDvDbl9irsEL7sVUh2muSK5lGMTUOA6l+AuiemBEn+ftwmbCTmJ81DaaOc38rk3etjMxMJ/KF8+ObUVXC2JNPcG2UtsfdOw/d4Upwanp2WJeD/0=,iv:BdkIQuxKRVFLrMf+j0goTiseY1r4ANsVd8UfkMxXWxk=,tag:B3eTCTV+cySoX1qaWcFxFA==,type:str]
sops:
    age:
        - recipient: age1646qm78yl7jgjue8fkseywxn322sdg47jtrqqhvypcfsx6k3e96qj5564c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlOVhmZFJnMGRDTGI5ZnFj
            MUl5THNXUzdsYWlKNUNjaGY3UGN4YzBwem1ZCkllN1N0K0xaYi84L3FRdWlCekFq
            N281RXV1NFE1ZThNcTgzWDZJTk03S0kKLS0tIEhiZEkxbXE0ZW5PbXF2WFNkcW43
            enNzQjlVc0J2c3BJaWhMYjRnUDhzd1kK7PK14HN1BrThls+xQfR54tmNolEw3EZQ
            zxY10e+i5mRWy5Iuwo0fE8NYPmax08HV7SEqVD+jLVfIiobsqUvrTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-26T16:58:11Z"
    mac: ENC[AES256_GCM,data:lYIz9Y2auAnKmZWa3koHcFcZ1kDEYf2oe2XtXMBY3rLOloYGdUfUkpFHhagoQp+ueH5vKr2BMDEq8tYRnMJHb/rttKxUkKT4syPL0yp8zXINZ89VfxFieJe9AWqGNNioEXxBc0uQP3Zc/hev7nWyO+wy8czNURJIuZL3Ms9HQEQ=,iv:h5LKGBlkM1MoDxuGWTxGsHghnKuP8S2OlhY8mdMuksw=,tag:5nxrxHEeXIks1JzzhKXkDg==,type:str]
    encrypted_regex: ^(data|stringData|certs|secrets|cluster|token)$
    mac_only_encrypted: true
    version: 3.10.2
