apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:h5OaMpWLp1Xpr7X4Y5biJdZ/Bx7/RQihAUm/7OzyDfhJB/mQcms9aDXMIhwnHfiHAm33xsCckAjnEmxF/Ggg6Cy4BBDXFe/TvlhSgF31ySjKXIcE2qHwc+QwM6dUH4Eazh5CkYXOUEXSvmm7vjFau1mkBDpUkYrQbnqpiPDLFlm2KWm8ITKvn87DwRU3rKppskZwkTzVy9riG7q1iHimcpVq+M0SfaOAb+SXo6OTJRq8v8rAj2i4JdNt88fDRe4n/gh5y2l6LJAzq8NkomI6oTTZ9EVnqBByMVp2JFQ5HOzsG23CpnWNXswrdfg=,iv:1i2ZWRlPErotkzoepBmc7/xU/tBd7NclxekvBkzMC8k=,tag:VeIdyu4T1531PJHud5YpaA==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: cloudflared
sops:
    age:
        - recipient: age1646qm78yl7jgjue8fkseywxn322sdg47jtrqqhvypcfsx6k3e96qj5564c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVSHZmbHZTV2pPNVlIUDNh
            eHZ0cHZGUFlNcTA1TFZJekgzbWIwQmx3WkRzCnptY2lvR0MvZkR1MXMwQzJIak00
            UnF0UEJVVXBheFFQRCtHMjdBVzBtZDQKLS0tIHNKdE5DRVh0bk5NY3JiSE0yOEFr
            eElHaUJyMzFLU1BBSDg4dnUzcVEwNkEK8Ca5u4353qCuPmKMZuHxFzINst5ApThS
            mscypmzg6bykw6nYOWtrFNi/m7zqhQGqNbHu1VXNPTFJ/5pOaJZLzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-26T11:13:18Z"
    mac: ENC[AES256_GCM,data:D9f3Z9PwvD/0lmYDLVL9SSaOLtm6DqM+sxSJjR6zL/JILtmtOy1GxfYCK+kk4Ao3/fWdQYI3VsXkMDfndcHxoAChS5u5GCV0HVknv6glcH45iHhBEc+uv84euoGrUJVlx0sxkvgcFXjyHyt9EydnxjLPhSUy7o08d86u+U0yrr8=,iv:/eHOirbsXA8TlTIM0br0e7KF9NVpl0Y8CxmlUr86wgY=,tag:myWnrEkThuFEPcj6lWsrTA==,type:str]
    encrypted_regex: ^(data|stringData|certs|secrets|cluster|token)$
    mac_only_encrypted: true
    version: 3.10.2
