---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: flux-system
spec:
  chart:
    spec:
      chart: longhorn
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
      version: 1.9.1
  install:
    crds: Create
    disableWait: true
  interval: 1m0s
  releaseName: longhorn
  targetNamespace: longhorn-system
  upgrade:
    crds: CreateReplace
    disableWait: true
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    ingress:
      enabled: true
      ingressClassName: traefik
      host: longhorn.local
      tls: true
      secureBackends: true
      tlsSecret: longhorn-tls
      path: /
    defaultSettings:
      storageReservedPercentageForDefaultDisk: 15
      storageOverProvisioningPercentage: 200
      defaultClassReplicaCount: 2
