---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudflared
  namespace: cloudflared
spec:
  interval: 5m
  chart:
    spec:
      chart: cloudflared
      version: 2.1.2
      sourceRef:
        kind: HelmRepository
        name: cloudflared
        namespace: flux-system
      interval: 5m
  values:
    tunnelSecrets:
      existingConfigJsonFileSecret:
        name: cloudflared-config
      existingPemFileSecret:
        name: tunnel-credentials

