#SPDX-License-Identifier: MIT-0
---
- name: Install Docker
  package:
    name: docker.io
    state: present

- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: true

- name: Add "{{ username }}" to docker group
  user:
    name: "{{ username }}"
    groups: docker
    append: true

- name: Check if Docker Swarm is already initialized
  stat:
    path: /var/lib/docker/swarm
  register: swarmEnabled

- name: Initialize Docker Swarm
  command: docker swarm init --advertise-addr "{{ HOSTADDRESS }}"
  when: not swarmEnabled.stat.exists
  register: swarm_init
  ignore_errors: true

- name: Show Swarm join token
  command: docker swarm join-token worker -q
  register: worker_token
  changed_when: false

- debug:
    msg: "Worker join token: {{ worker_token.stdout }}"
