#SPDX-License-Identifier: MIT-0
---
- name: Install Docker
  package:
    name: docker.io
    state: present

- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: true

- name: Add "{{ username }}" to docker group
  user:
    name: "{{ username }}"
    groups: docker
    append: true
